# Generated by Django 5.2 on 2025-06-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LargeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('organization_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('pan_id', models.CharField(blank=True, max_length=80, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('country_code', models.CharField(max_length=4)),
                ('mobile', models.CharField(blank=True, max_length=80, null=True)),
                ('is_whatsapp_verified', models.BooleanField(default=False)),
                ('payment_term', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('total_payment_amount_received', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('total_amount_sales', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('customer_type', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_level', models.CharField(default='LEVEL-1', max_length=50)),
                ('parents_count', models.PositiveSmallIntegerField(default=0)),
                ('level_3_customer_count', models.PositiveSmallIntegerField(default=0)),
                ('level_2_customer_count', models.PositiveSmallIntegerField(default=0)),
                ('customer_parent_id', models.IntegerField(blank=True, null=True)),
                ('distributor_id', models.IntegerField(blank=True, null=True)),
                ('segment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('segment_discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('pricing_group_id', models.IntegerField(blank=True, null=True)),
                ('whatsapp_opt', models.BooleanField(default=False)),
                ('customer_consent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_all_staff', models.BooleanField(default=False)),
                ('allow_all_beats', models.BooleanField(default=False)),
                ('allow_all_pro_cat', models.BooleanField(default=False)),
                ('custom_form_data', models.JSONField(blank=True, default=list)),
                ('accounts_sw_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
